[#ftl]
[@pp.dropOutputFile /]
[@pp.changeOutputFile name="lcd_conf.h" /]

 /*
  * lcd_conf.h
  */
[#assign group = conf.instance.lcd_settings]
  [#assign size = group.working_mode.matrix_size.value[0] /]
  [#assign rows = group.working_mode.number_of_rows.value[0] /]
  [#assign transfer = group.working_mode.transfer_mode.value[0] /]
  [#assign cursdir = group.editing_mode.cursor_direction.value[0] /]
  [#assign display = group.editing_mode.show_display.value[0] /]
  [#assign cursor = group.editing_mode.show_cursor.value[0] /]
  [#assign blinking = group.editing_mode.blinking.value[0] /]
  [#assign mode = group.working_mode.transfer_mode.value[0] /]
  [#assign i2ccomp = group.working_mode.i2c_component.value[0] /]
#ifndef _LCDCONF_H_
#define _LCDCONF_H_

[#if mode=="gpio-8bits"]
[#assign ok = false]
[#list global.instances["com.st.spc5.components.board.spc560dxx_rla"].i_o_settings.pins_list.pin_settings as ss ]
[#if conf.instance.lcd_settings.io_settings_mapping.*.d0.value[0] == ss.pin_identification.identifier.value[0]]
[#assign ok = true]
[#assign pin = ss.pin_identification.identifier.value[0]]
[#assign port = ss.pin_identification.port.value[0]]
[/#if]
[/#list]
[#if ok == true]
#define LCD_PORT_DB0	${port}
[#else]
#define LCD_PORT_DB0	#error  please choose a valid pin identifier ***
[/#if]
[#assign ok = false]
[#list global.instances["com.st.spc5.components.board.spc560dxx_rla"].i_o_settings.pins_list.pin_settings as ss ]
[#if conf.instance.lcd_settings.io_settings_mapping.*.d1.value[0] == ss.pin_identification.identifier.value[0]]
[#assign ok = true]
[#assign pin = ss.pin_identification.identifier.value[0]]
[#assign port = ss.pin_identification.port.value[0]]
[/#if]
[/#list]
[#if ok == true]
#define LCD_PORT_DB1	${port}
[#else]
#define LCD_PORT_DB1	#error  please choose a valid pin identifier ***
[/#if]
[#assign ok = false]
[#list global.instances["com.st.spc5.components.board.spc560dxx_rla"].i_o_settings.pins_list.pin_settings as ss ]
[#if conf.instance.lcd_settings.io_settings_mapping.*.d2.value[0] == ss.pin_identification.identifier.value[0]]
[#assign ok = true]
[#assign pin = ss.pin_identification.identifier.value[0]]
[#assign port = ss.pin_identification.port.value[0]]
[/#if]
[/#list]
[#if ok == true]
#define LCD_PORT_DB2	${port}
[#else]
#define LCD_PORT_DB2	#error  please choose a valid pin identifier ***
[/#if]
[#assign ok = false]
[#list global.instances["com.st.spc5.components.board.spc560dxx_rla"].i_o_settings.pins_list.pin_settings as ss ]
[#if conf.instance.lcd_settings.io_settings_mapping.*.d3.value[0] == ss.pin_identification.identifier.value[0]]
[#assign ok = true]
[#assign pin = ss.pin_identification.identifier.value[0]]
[#assign port = ss.pin_identification.port.value[0]]
[/#if]
[/#list]
[#if ok == true]
#define LCD_PORT_DB3	${port}
[#else]
#define LCD_PORT_DB3	#error  please choose a valid pin identifier ***
[/#if]
[/#if]
[#if mode != "i2c"]
[#assign ok = false]
[#list global.instances["com.st.spc5.components.board.spc560dxx_rla"].i_o_settings.pins_list.pin_settings as ss ]
[#if conf.instance.lcd_settings.io_settings_mapping.*.d4.value[0] == ss.pin_identification.identifier.value[0]]
[#assign ok = true]
[#assign pin = ss.pin_identification.identifier.value[0]]
[#assign port = ss.pin_identification.port.value[0]]
[/#if]
[/#list]
[#if ok == true]
#define LCD_PORT_DB4	${port}
[#else]
#define LCD_PORT_DB4	#error  please choose a valid pin identifier ***
[/#if]
[#assign ok = false]
[#list global.instances["com.st.spc5.components.board.spc560dxx_rla"].i_o_settings.pins_list.pin_settings as ss ]
[#if conf.instance.lcd_settings.io_settings_mapping.*.d5.value[0] == ss.pin_identification.identifier.value[0]]
[#assign ok = true]
[#assign pin = ss.pin_identification.identifier.value[0]]
[#assign port = ss.pin_identification.port.value[0]]
[/#if]
[/#list]
[#if ok == true]
#define LCD_PORT_DB5	${port}
[#else]
#define LCD_PORT_DB5	#error  please choose a valid pin identifier ***
[/#if]
[#assign ok = false]
[#list global.instances["com.st.spc5.components.board.spc560dxx_rla"].i_o_settings.pins_list.pin_settings as ss ]
[#if conf.instance.lcd_settings.io_settings_mapping.*.d6.value[0] == ss.pin_identification.identifier.value[0]]
[#assign ok = true]
[#assign pin = ss.pin_identification.identifier.value[0]]
[#assign port = ss.pin_identification.port.value[0]]
[/#if]
[/#list]
[#if ok == true]
#define LCD_PORT_DB6	${port}
[#else]
#define LCD_PORT_DB6	#error  please choose a valid pin identifier ***
[/#if]
[#assign ok = false]
[#list global.instances["com.st.spc5.components.board.spc560dxx_rla"].i_o_settings.pins_list.pin_settings as ss ]
[#if conf.instance.lcd_settings.io_settings_mapping.*.d7.value[0] == ss.pin_identification.identifier.value[0]]
[#assign ok = true]
[#assign pin = ss.pin_identification.identifier.value[0]]
[#assign port = ss.pin_identification.port.value[0]]
[/#if]
[/#list]
[#if ok == true]
#define LCD_PORT_DB7	${port}
[#else]
#define LCD_PORT_DB7	#error  please choose a valid pin identifier ***
[/#if]
[#assign ok = false]
[#list global.instances["com.st.spc5.components.board.spc560dxx_rla"].i_o_settings.pins_list.pin_settings as ss ]
[#if conf.instance.lcd_settings.io_settings_mapping.*.rs.value[0] == ss.pin_identification.identifier.value[0]]
[#assign ok = true]
[#assign pin = ss.pin_identification.identifier.value[0]]
[#assign port = ss.pin_identification.port.value[0]]
[/#if]
[/#list]
[#if ok == true]
#define LCD_PORT_RS		${port}
[#else]
#define LCD_PORT_RS		#error  please choose a valid pin identifier ***
[/#if]
[#assign ok = false]
[#list global.instances["com.st.spc5.components.board.spc560dxx_rla"].i_o_settings.pins_list.pin_settings as ss ]
[#if conf.instance.lcd_settings.io_settings_mapping.*.rw.value[0] == ss.pin_identification.identifier.value[0]]
[#assign ok = true]
[#assign pin = ss.pin_identification.identifier.value[0]]
[#assign port = ss.pin_identification.port.value[0]]
[/#if]
[/#list]
[#if ok == true]
#define LCD_PORT_RW		${port}
[#else]
#define LCD_PORT_RW		#error  please choose a valid pin identifier ***
[/#if]
[#assign ok = false]
[#list global.instances["com.st.spc5.components.board.spc560dxx_rla"].i_o_settings.pins_list.pin_settings as ss ]
[#if conf.instance.lcd_settings.io_settings_mapping.*.e.value[0] == ss.pin_identification.identifier.value[0]]
[#assign ok = true]
[#assign pin = ss.pin_identification.identifier.value[0]]
[#assign port = ss.pin_identification.port.value[0]]
[/#if]
[/#list]
[#if ok == true]
#define LCD_PORT_E		${port}
[#else]
#define LCD_PORT_E		#error  please choose a valid pin identifier ***
[/#if]

[/#if]
#endif /* _LCDCONF_H_ */
